# Generated by Django 3.2.9 on 2021-11-18 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('order_number', models.PositiveIntegerField(default=None, null=True, unique=True, verbose_name='Номер заказа')),
                ('customer_chat_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='Chat ID Покупателя')),
                ('order_price', models.PositiveIntegerField(default=0, verbose_name='Цена заказа')),
                ('comments', models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='ID пользователя в сети')),
                ('first_name', models.CharField(blank=True, max_length=10, verbose_name='Имя пользователя')),
                ('patronymic', models.CharField(blank=True, max_length=10, verbose_name='Отчество пользователя')),
                ('last_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='Фамилия пользователя')),
                ('tg_chat_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='Chat ID Покупателя')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон пользователя')),
                ('passport_date', models.IntegerField(blank=True, default=0, verbose_name='Пасспортные данные')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('home_address', models.CharField(blank=True, default='', max_length=50, verbose_name='Домашний адрес')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Stuff_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Категория вещей',
                'verbose_name_plural': 'Категорий вещей',
            },
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuff_name', models.CharField(max_length=256, verbose_name='Назвние вещи')),
                ('price_per_week', models.PositiveIntegerField(default=100, verbose_name='Цена за неделю')),
                ('price_per_month', models.PositiveIntegerField(default=100, verbose_name='Цена за месяц')),
                ('stuff_categories', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agent_bot.stuff_categories')),
            ],
            options={
                'verbose_name': 'Свойства вещи',
                'verbose_name_plural': 'Свойства вещей',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_volume', models.PositiveIntegerField(verbose_name='Объем ячейки')),
                ('storage_address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Адрес ячейки')),
                ('start_date', models.DateField(verbose_name='Дата начала аренды')),
                ('end_date', models.DateField(verbose_name='Дата окончания аренды')),
                ('order_status', models.CharField(choices=[('Ячейка доступна', 'Ячейка доступна'), ('Ячейка недоступна', 'Ячейка недоступна')], default='Ячейка доступна', max_length=256, verbose_name='Статус заказа')),
                ('qr_code', models.ImageField(upload_to='static/qr')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent_bot.order', verbose_name='Заказ')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent_bot.profile', verbose_name='Профиль'),
        ),
    ]
