# Generated by Django 3.2.9 on 2021-11-17 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuff_name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Вещь',
                'verbose_name_plural': 'Вещи',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_chat_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Chat ID Покупателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(default=None, null=True, unique=True, verbose_name='Номер заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена заказа'),
        ),
        migrations.AddField(
            model_name='profile',
            name='GDPR_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='home_address',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Домашний адрес'),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport_date',
            field=models.IntegerField(blank=True, default=0, verbose_name='Пасспортные данные'),
        ),
        migrations.AddField(
            model_name='profile',
            name='patronymic',
            field=models.CharField(blank=True, max_length=10, verbose_name='Отчество пользователя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent_bot.profile', verbose_name='Профиль'),
        ),
        migrations.CreateModel(
            name='Stuff_properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_week', models.PositiveIntegerField(verbose_name='Цена за неделю')),
                ('price_per_month', models.PositiveIntegerField(verbose_name='Цена за месяц')),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent_bot.stuff')),
            ],
            options={
                'verbose_name': 'Свойства вещи',
                'verbose_name_plural': 'Свойства вещей',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_volume', models.PositiveIntegerField(verbose_name='Объем ячейки')),
                ('storage_address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Адрес ячейки')),
                ('start_date', models.DateField(verbose_name='Дата начала аренды')),
                ('end_date', models.DateField(verbose_name='Дата окончания аренды')),
                ('order_status', models.CharField(choices=[('Ячейка доступна', 'Ячейка доступна'), ('Ячейка недоступна', 'Ячейка недоступна')], default='Ячейка доступна', max_length=256, verbose_name='Статус заказа')),
                ('qr_code', models.ImageField(upload_to='static/qr')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent_bot.order', verbose_name='Заказ')),
            ],
        ),
    ]
